/**
 * sync-abi.ts
 *
 * Reads compiled contract ABIs from `hardhat/artifacts/` and writes them out
 * as typed `as const` TypeScript modules under `web/src/abi/`, so the Next.js
 * frontend always uses the exact ABI that matches the currently compiled
 * Solidity source — no more manually copy-pasting ABI JSON between packages.
 *
 * Usage (from the `hardhat/` directory):
 *   npx hardhat compile && npx tsx scripts/sync-abi.ts
 *   npm run sync-abi   // runs both steps, see package.json
 *
 * Add a contract name to CONTRACTS below to have it synced as well.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const HARDHAT_ROOT = path.resolve(__dirname, "..");
const ARTIFACTS_DIR = path.join(HARDHAT_ROOT, "artifacts", "contracts");
const WEB_ABI_DIR = path.resolve(HARDHAT_ROOT, "..", "web", "src", "abi");

/** contractName -> path to the .sol file (relative to contracts/) it lives in. */
const CONTRACTS: Record<string, string> = {
  AIJudge: "AIJudge.sol",
};

type Artifact = {
  contractName: string;
  abi: unknown[];
};

async function loadArtifact(contractName: string, solFile: string): Promise<Artifact> {
  const artifactPath = path.join(
    ARTIFACTS_DIR,
    solFile,
    `${contractName}.json`,
  );

  if (!existsSync(artifactPath)) {
    throw new Error(
      `Artifact not found for ${contractName} at ${artifactPath}.\n` +
        `Did you run "npx hardhat compile" first?`,
    );
  }

  const raw = await readFile(artifactPath, "utf-8");
  const parsed = JSON.parse(raw) as Artifact;
  return parsed;
}

function renderModule(contractName: string, abi: unknown[]): string {
  const json = JSON.stringify(abi, null, 2);
  return `// AUTO-GENERATED by hardhat/scripts/sync-abi.ts — do not edit by hand.
// Source of truth: hardhat/contracts/${contractName}.sol
// Regenerate with: npx hardhat compile && npx tsx scripts/sync-abi.ts

const abi = ${json} as const;

export default abi;
`;
}

async function main() {
  if (!existsSync(ARTIFACTS_DIR)) {
    throw new Error(
      `No artifacts directory found at ${ARTIFACTS_DIR}.\n` +
        `Run "npx hardhat compile" before syncing the ABI.`,
    );
  }

  await mkdir(WEB_ABI_DIR, { recursive: true });

  const written: string[] = [];

  for (const [contractName, solFile] of Object.entries(CONTRACTS)) {
    const artifact = await loadArtifact(contractName, solFile);
    const outFile = path.join(WEB_ABI_DIR, `${contractName}.ts`);
    await writeFile(outFile, renderModule(contractName, artifact.abi), "utf-8");
    written.push(path.relative(path.resolve(HARDHAT_ROOT, ".."), outFile));
  }

  console.log("ABI sync complete:");
  for (const file of written) {
    console.log(`  -> ${file}`);
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
